### ISSUE TITLE
Ошибка при запуске.

### ISSUE THREAD

**Issue by Kot-nikot** [ef1f/AceSearch#1]
Проект еще жив?
Пытаюсь установить на Ubuntu  22.04. установлен Net 7.0.17
`$ dotnet --info

Host:
  Version:      7.0.17
  Architecture: x64
  Commit:       dff486f2d7

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 7.0.17 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]
`
При запуске получаю следующую ошибку:
`$ dotnet AceSearch.dll appsettings.json
Unhandled exception. System.ArgumentException: The path must be absolute. (Parameter 'root')
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.Extensions.Configuration.FileConfigurationExtensions.SetBasePath(IConfigurationBuilder builder, String basePath)
   at AceSearch.Program.Main(String[] args) in /src/AceSearch/src/Program.cs:line 30
   at AceSearch.Program.<Main>(String[] args)
Аварийный останов (образ памяти сброшен на диск)
`

**Comment by Kot-nikot** [comment]
Все работает, разобрался.
